baseURL = "https://blog.superwm.top/"
languageCode = "en-us"
title = "wm's blog"

theme = "hugo-ficurinia"

author = "wm"
copyright = ""

paginate = 5
summaryLength = 30

[params]
    description = "Curiosity of everything"
    author = "wm"
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"
    # commento = "https://cloud.techpills.technology:54321/js/commento.js"
    cactusCommentsSiteName = "blog.superwm.top"
    #cactusCommentsServerName = "cactus.chat"
    #cactusCommentsHomeserver = "https://matrix.cactus.chat:8448"
    
    imageInArticlePreview = true

    enableShareOnFediverse = true

    enableRelatedArticles = true
    relatedArticlesNum = 2 
    forceRedirect = false

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.icons]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/wwminger"
        weight = 10
